apiVersion: v1
kind: Secret
metadata:
  name: agrostream-secrets
type: Opaque
stringData:
  POSTGRES_USER: "<YOUR_POSTGRES_USER>"
  POSTGRES_PASSWORD: "<YOUR_POSTGRES_PASSWORD>"
  POSTGRES_HOST: "<YOUR_POSTGRES_HOST>"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "agrostream"
  KAFKA_BOOTSTRAP_SERVERS: "<YOUR_KAFKA_HOST>:9092"
